-- =========================================
-- Cocina DeLicia - Schema Consolidado Sprint 5
-- Compatible con H2 (modo PostgreSQL) y PostgreSQL real
-- Incluye: catálogo, variantes, modifiers, imágenes, pedidos, usuarios
-- =========================================

-- ===============================
-- 1. CATÁLOGO BASE
-- ===============================

CREATE TABLE IF NOT EXISTS category (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(191) NOT NULL,
  slug        VARCHAR(191) NOT NULL,
  description TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP,
  CONSTRAINT uk_category_name UNIQUE (name),
  CONSTRAINT uk_category_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS tag (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(191) NOT NULL,
  slug        VARCHAR(191) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP,
  CONSTRAINT uk_tag_name UNIQUE (name),
  CONSTRAINT uk_tag_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS product (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id      BIGINT NOT NULL,
  name             VARCHAR(191) NOT NULL,
  slug             VARCHAR(191) NOT NULL,
  description      TEXT,
  tax_rate_percent NUMERIC(5,2) NOT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  -- Sprint 5: Flags de marketing (source of truth a nivel producto)
  is_featured      BOOLEAN NOT NULL DEFAULT FALSE,
  is_daily_menu    BOOLEAN NOT NULL DEFAULT FALSE,
  is_new           BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMP,
  CONSTRAINT uk_product_slug UNIQUE (slug),
  CONSTRAINT fk_product_category FOREIGN KEY (category_id)
    REFERENCES category(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_product_category ON product (category_id);
CREATE INDEX IF NOT EXISTS idx_product_active ON product (is_active, deleted_at);
CREATE INDEX IF NOT EXISTS idx_product_featured ON product (is_featured);
CREATE INDEX IF NOT EXISTS idx_product_daily_menu ON product (is_daily_menu);

CREATE TABLE IF NOT EXISTS product_tag (
  product_id BIGINT NOT NULL,
  tag_id     BIGINT NOT NULL,
  CONSTRAINT pk_product_tag PRIMARY KEY (product_id, tag_id),
  CONSTRAINT fk_pt_product FOREIGN KEY (product_id) REFERENCES product(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_pt_tag FOREIGN KEY (tag_id) REFERENCES tag(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- ===============================
-- 2. VARIANTES Y PRECIOS
-- ===============================

CREATE TABLE IF NOT EXISTS product_variant (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     BIGINT NOT NULL,
  sku            VARCHAR(191),
  name           VARCHAR(191) NOT NULL,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  -- Stock management
  manages_stock  BOOLEAN NOT NULL DEFAULT FALSE,
  stock_quantity INT NOT NULL DEFAULT 0,
  -- Flags heredados (para retrocompatibilidad)
  is_featured    BOOLEAN NOT NULL DEFAULT FALSE,
  is_daily_menu  BOOLEAN NOT NULL DEFAULT FALSE,
  is_new         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at     TIMESTAMP,
  CONSTRAINT uk_variant_sku UNIQUE (sku),
  CONSTRAINT fk_variant_product FOREIGN KEY (product_id)
    REFERENCES product(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_variant_stock_quantity_non_negative CHECK (stock_quantity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_variant_product ON product_variant (product_id);
CREATE INDEX IF NOT EXISTS idx_variant_sku ON product_variant (sku);
CREATE INDEX IF NOT EXISTS idx_variant_active ON product_variant (product_id, is_active, deleted_at);

CREATE TABLE IF NOT EXISTS price_history (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_variant_id BIGINT NOT NULL,
  price              NUMERIC(10,2) NOT NULL,
  currency           VARCHAR(3) NOT NULL,
  valid_from         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_to           TIMESTAMP,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at         TIMESTAMP,
  CONSTRAINT fk_ph_variant FOREIGN KEY (product_variant_id)
    REFERENCES product_variant(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_currency CHECK (currency IN ('UYU','USD'))
);

CREATE INDEX IF NOT EXISTS idx_ph_variant_from ON price_history (product_variant_id, valid_from);
CREATE INDEX IF NOT EXISTS idx_ph_variant_to ON price_history (product_variant_id, valid_to);
-- Nota: índice parcial (WHERE valid_to IS NULL) no soportado en H2, usar consulta filtrada

-- ===============================
-- 3. IMÁGENES DE PRODUCTO
-- ===============================

CREATE TABLE IF NOT EXISTS product_image (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  object_key VARCHAR(512) NOT NULL,
  is_main    BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT fk_product_image_product FOREIGN KEY (product_id)
    REFERENCES product(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_product_image_sort_order_non_negative CHECK (sort_order >= 0),
  CONSTRAINT uk_product_image_product_key UNIQUE (product_id, object_key)
);

CREATE INDEX IF NOT EXISTS idx_product_image_product ON product_image (product_id);
CREATE INDEX IF NOT EXISTS idx_product_image_main ON product_image (product_id, is_main);
CREATE INDEX IF NOT EXISTS idx_product_image_sort ON product_image (product_id, sort_order);

-- ===============================
-- 4. MODIFIERS (Sprint 5)
-- ===============================

CREATE TABLE IF NOT EXISTS modifier_group (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_variant_id BIGINT NOT NULL,
  name               VARCHAR(191) NOT NULL,
  min_select         INT NOT NULL DEFAULT 0,
  max_select         INT NOT NULL DEFAULT 1,
  selection_mode     VARCHAR(20) NOT NULL DEFAULT 'SINGLE',
  required_total_qty INT,
  default_option_id  BIGINT,
  sort_order         INT NOT NULL DEFAULT 0,
  is_active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at         TIMESTAMP,
  CONSTRAINT fk_modifier_group_variant FOREIGN KEY (product_variant_id)
    REFERENCES product_variant(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_modifier_group_selection_mode CHECK (selection_mode IN ('SINGLE','MULTI','QTY')),
  CONSTRAINT chk_modifier_group_bounds CHECK (max_select >= 0 AND min_select >= 0)
);

CREATE INDEX IF NOT EXISTS idx_modifier_group_variant ON modifier_group (product_variant_id);
CREATE INDEX IF NOT EXISTS idx_modifier_group_active ON modifier_group (product_variant_id, is_active, sort_order);

CREATE TABLE IF NOT EXISTS modifier_option (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id                  BIGINT NOT NULL,
  name                      VARCHAR(191) NOT NULL,
  sort_order                INT NOT NULL DEFAULT 0,
  is_active                 BOOLEAN NOT NULL DEFAULT TRUE,
  price_delta               NUMERIC(10,2),
  is_exclusive              BOOLEAN NOT NULL DEFAULT FALSE,
  linked_product_variant_id BIGINT,
  created_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at                TIMESTAMP,
  CONSTRAINT fk_modifier_option_group FOREIGN KEY (group_id)
    REFERENCES modifier_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_modifier_option_variant FOREIGN KEY (linked_product_variant_id)
    REFERENCES product_variant(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_modifier_option_group ON modifier_option (group_id);
CREATE INDEX IF NOT EXISTS idx_modifier_option_variant ON modifier_option (linked_product_variant_id);

-- FK circular: default_option_id -> modifier_option
ALTER TABLE modifier_group
  ADD CONSTRAINT fk_modifier_group_default_option
  FOREIGN KEY (default_option_id) REFERENCES modifier_option(id)
    ON UPDATE RESTRICT ON DELETE SET NULL;

-- ===============================
-- 5. USUARIOS Y ROLES
-- ===============================

CREATE TABLE IF NOT EXISTS app_user (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cognito_user_id VARCHAR(191) NOT NULL,
  first_name      VARCHAR(191) NOT NULL,
  last_name       VARCHAR(191) NOT NULL,
  email           VARCHAR(191) NOT NULL,
  phone           VARCHAR(50),
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at      TIMESTAMP,
  CONSTRAINT uk_user_cognito_id UNIQUE (cognito_user_id),
  CONSTRAINT uk_user_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_user_email ON app_user (email);
CREATE INDEX IF NOT EXISTS idx_user_cognito ON app_user (cognito_user_id);

CREATE TABLE IF NOT EXISTS role (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP,
  CONSTRAINT uk_role_name UNIQUE (name),
  CONSTRAINT chk_role_name CHECK (name IN ('ADMIN','CHEF','COURIER','CUSTOMER'))
);

CREATE TABLE IF NOT EXISTS user_role (
  user_id     BIGINT NOT NULL,
  role_id     BIGINT NOT NULL,
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES app_user(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES role(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS customer_address (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  label       VARCHAR(100),
  line1       VARCHAR(191) NOT NULL,
  line2       VARCHAR(191),
  city        VARCHAR(100) NOT NULL,
  region      VARCHAR(100),
  postal_code VARCHAR(20),
  reference   VARCHAR(191),
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP,
  CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES app_user(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_address_user ON customer_address (user_id);

-- ===============================
-- 6. PEDIDOS Y CHECKOUT
-- ===============================

CREATE TABLE IF NOT EXISTS customer_order (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,
  status           VARCHAR(30) NOT NULL,
  fulfillment      VARCHAR(30) NOT NULL,
  currency         VARCHAR(3) NOT NULL,
  subtotal_amount  NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  tax_amount       NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  discount_amount  NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_amount     NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  -- Snapshot de envío
  ship_name        VARCHAR(191),
  ship_phone       VARCHAR(50),
  ship_line1       VARCHAR(191),
  ship_line2       VARCHAR(191),
  ship_city        VARCHAR(100),
  ship_region      VARCHAR(100),
  ship_postal_code VARCHAR(20),
  ship_reference   VARCHAR(191),
  notes            TEXT,
  -- Timestamps de flujo
  requested_at     TIMESTAMP,
  delivered_at     TIMESTAMP,
  -- Audit
  deleted_by       VARCHAR(255),
  assigned_chef_email VARCHAR(255),
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMP,
  CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES app_user(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_order_status CHECK (
    status IN ('CREATED','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')
  ),
  CONSTRAINT chk_fulfillment CHECK (fulfillment IN ('PICKUP','DELIVERY')),
  CONSTRAINT chk_order_currency CHECK (currency IN ('UYU','USD'))
);

CREATE INDEX IF NOT EXISTS idx_order_user_created ON customer_order (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_order_status_created ON customer_order (status, created_at);
CREATE INDEX IF NOT EXISTS idx_order_requested_at ON customer_order (requested_at);
CREATE INDEX IF NOT EXISTS idx_order_deleted_at ON customer_order (deleted_at);
CREATE INDEX IF NOT EXISTS idx_order_assigned_chef ON customer_order (assigned_chef_email);
CREATE INDEX IF NOT EXISTS idx_order_fulfillment_requested ON customer_order (fulfillment, requested_at);

CREATE TABLE IF NOT EXISTS order_item (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id           BIGINT NOT NULL,
  product_id         BIGINT NOT NULL,
  product_variant_id BIGINT NOT NULL,
  product_name       VARCHAR(191) NOT NULL,
  variant_name       VARCHAR(191) NOT NULL,
  unit_price         NUMERIC(10,2) NOT NULL,
  quantity           INT NOT NULL DEFAULT 1,
  line_total         NUMERIC(10,2) NOT NULL,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at         TIMESTAMP,
  CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES customer_order(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES product(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_item_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_item_order ON order_item (order_id);
CREATE INDEX IF NOT EXISTS idx_order_item_product_id ON order_item (product_id);
CREATE INDEX IF NOT EXISTS idx_order_item_product_variant_id ON order_item (product_variant_id);

-- ===============================
-- 7. MODIFIERS EN PEDIDOS (Sprint 5)
-- ===============================

CREATE TABLE IF NOT EXISTS order_item_modifier (
  id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_item_id                     BIGINT NOT NULL,
  modifier_option_id                BIGINT NOT NULL,
  quantity                          INT NOT NULL DEFAULT 1,
  option_name_snapshot              VARCHAR(191) NOT NULL,
  price_delta_snapshot              NUMERIC(10,2),
  unit_price_snapshot               NUMERIC(10,2),
  total_price_snapshot              NUMERIC(10,2),
  linked_product_variant_id_snapshot BIGINT,
  created_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at                        TIMESTAMP,
  CONSTRAINT fk_order_item_modifier_order_item FOREIGN KEY (order_item_id)
    REFERENCES order_item(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_order_item_modifier_option FOREIGN KEY (modifier_option_id)
    REFERENCES modifier_option(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_order_item_modifier_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_order_item_modifier_order ON order_item_modifier (order_item_id);
CREATE INDEX IF NOT EXISTS idx_order_item_modifier_option ON order_item_modifier (modifier_option_id);

-- ===============================
-- 8. HISTORIAL DE ESTADO DE PEDIDOS
-- ===============================

CREATE TABLE IF NOT EXISTS order_status_history (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT NOT NULL,
  from_status VARCHAR(30),
  to_status   VARCHAR(30) NOT NULL,
  changed_by  VARCHAR(255) NOT NULL,
  changed_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reason      VARCHAR(500),
  CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id)
    REFERENCES customer_order(id) ON DELETE CASCADE,
  CONSTRAINT chk_status_history_from CHECK (
    from_status IS NULL OR from_status IN ('CREATED','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')
  ),
  CONSTRAINT chk_status_history_to CHECK (
    to_status IN ('CREATED','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')
  )
);

CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON order_status_history (order_id);
CREATE INDEX IF NOT EXISTS idx_order_status_history_changed_at ON order_status_history (changed_at);

-- ===============================
-- 9. PAGOS
-- ===============================

CREATE TABLE IF NOT EXISTS payment (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       BIGINT NOT NULL,
  method         VARCHAR(30) NOT NULL,
  status         VARCHAR(30) NOT NULL,
  amount         NUMERIC(10,2) NOT NULL,
  currency       VARCHAR(3) NOT NULL,
  provider_tx_id VARCHAR(191),
  note           VARCHAR(255),
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at     TIMESTAMP,
  CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES customer_order(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_payment_method CHECK (
    method IN ('CASH','BANK_TRANSFER','MERCADOPAGO','CREDIT_CARD','DEBIT_CARD')
  ),
  CONSTRAINT chk_payment_status CHECK (
    status IN ('PENDING','AUTHORIZED','PAID','FAILED','REFUNDED','CANCELLED')
  ),
  CONSTRAINT chk_payment_currency CHECK (currency IN ('UYU','USD'))
);

CREATE INDEX IF NOT EXISTS idx_payment_order ON payment (order_id);
CREATE INDEX IF NOT EXISTS idx_payment_status_created ON payment (status, created_at);
