-- Migration V3: Add order status history table for audit trail
-- Author: System
-- Date: 2026-01-25

CREATE TABLE IF NOT EXISTS order_status_history (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT NOT NULL,
  from_status VARCHAR(30),
  to_status   VARCHAR(30) NOT NULL,
  changed_by  VARCHAR(255) NOT NULL,
  changed_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reason      VARCHAR(500),

  CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id)
    REFERENCES customer_order(id) ON DELETE CASCADE,

  CONSTRAINT chk_status_history_from CHECK (
    from_status IS NULL OR from_status IN ('CREATED','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELED')
  ),
  CONSTRAINT chk_status_history_to CHECK (
    to_status IN ('CREATED','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELED')
  )
);

CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON order_status_history(order_id);
CREATE INDEX IF NOT EXISTS idx_order_status_history_changed_at ON order_status_history(changed_at);

-- Add deleted_by column to customer_order if not exists
-- Note: deleted_at already exists in V1
ALTER TABLE customer_order ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- Add assigned_chef_email column
ALTER TABLE customer_order ADD COLUMN IF NOT EXISTS assigned_chef_email VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_order_deleted_at ON customer_order(deleted_at);
CREATE INDEX IF NOT EXISTS idx_order_assigned_chef ON customer_order(assigned_chef_email);
