-- =========================================
-- Sprint 6 - US07: Auditoría Persistente
-- Tabla para registrar acciones críticas sobre usuarios
-- =========================================

CREATE TABLE IF NOT EXISTS user_audit_log (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  action     VARCHAR(50) NOT NULL,
  changed_by VARCHAR(255) NOT NULL,
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  details    TEXT,
  CONSTRAINT fk_user_audit_user FOREIGN KEY (user_id)
    REFERENCES app_user(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_user_audit_user_changed_at
  ON user_audit_log (user_id, changed_at DESC);

-- Acciones esperadas:
-- USER_INVITED, USER_IMPORTED, ROLE_CHANGED, STATUS_CHANGED, USER_SYNCED
