-- S05.US08: Modifier groups, options y snapshots de order item
CREATE TABLE IF NOT EXISTS modifier_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_variant_id BIGINT NOT NULL,
  name VARCHAR(191) NOT NULL,
  min_select INT NOT NULL DEFAULT 0,
  max_select INT NOT NULL DEFAULT 1,
  selection_mode VARCHAR(20) NOT NULL DEFAULT 'SINGLE',
  required_total_qty INT,
  default_option_id BIGINT,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT fk_modifier_group_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_modifier_group_selection_mode CHECK (selection_mode IN ('SINGLE','MULTI','QTY')),
  CONSTRAINT chk_modifier_group_bounds CHECK (max_select >= 0 AND min_select >= 0)
);

CREATE INDEX IF NOT EXISTS idx_modifier_group_variant ON modifier_group (product_variant_id);
CREATE INDEX IF NOT EXISTS idx_modifier_group_active ON modifier_group (product_variant_id, is_active, sort_order);

CREATE TABLE IF NOT EXISTS modifier_option (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  name VARCHAR(191) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  price_delta NUMERIC(10,2),
  is_exclusive BOOLEAN NOT NULL DEFAULT FALSE,
  linked_product_variant_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT fk_modifier_option_group FOREIGN KEY (group_id) REFERENCES modifier_group(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_modifier_option_variant FOREIGN KEY (linked_product_variant_id) REFERENCES product_variant(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_modifier_option_group ON modifier_option (group_id);
CREATE INDEX IF NOT EXISTS idx_modifier_option_variant ON modifier_option (linked_product_variant_id);

ALTER TABLE modifier_group
  ADD CONSTRAINT fk_modifier_group_default_option
  FOREIGN KEY (default_option_id) REFERENCES modifier_option(id)
    ON UPDATE RESTRICT ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS order_item_modifier (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_item_id BIGINT NOT NULL,
  modifier_option_id BIGINT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  option_name_snapshot VARCHAR(191) NOT NULL,
  price_delta_snapshot NUMERIC(10,2),
  unit_price_snapshot NUMERIC(10,2),
  total_price_snapshot NUMERIC(10,2),
  linked_product_variant_id_snapshot BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT fk_order_item_modifier_order_item FOREIGN KEY (order_item_id) REFERENCES order_item(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_order_item_modifier_option FOREIGN KEY (modifier_option_id) REFERENCES modifier_option(id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_order_item_modifier_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_order_item_modifier_order ON order_item_modifier (order_item_id);
CREATE INDEX IF NOT EXISTS idx_order_item_modifier_option ON order_item_modifier (modifier_option_id);
