-- =========================================
-- Sprint S07 - US01: API de Carrito Backend
-- Tablas: cart, cart_item
-- Compatible con H2 (modo PostgreSQL) y PostgreSQL
-- =========================================

-- ===============================
-- TABLA: cart
-- ===============================
-- Carrito de compras persistente por usuario autenticado

CREATE TABLE IF NOT EXISTS cart (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP,

  CONSTRAINT fk_cart_user FOREIGN KEY (user_id)
    REFERENCES app_user(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- Índices para cart
CREATE INDEX IF NOT EXISTS idx_cart_user ON cart (user_id);
CREATE INDEX IF NOT EXISTS idx_cart_active ON cart (user_id, deleted_at);

-- ===============================
-- TABLA: cart_item
-- ===============================
-- Items individuales dentro del carrito
-- Modifiers se guardan como JSON para snapshot inmutable

CREATE TABLE IF NOT EXISTS cart_item (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id            BIGINT NOT NULL,
  product_id         BIGINT NOT NULL,
  product_variant_id BIGINT NOT NULL,

  -- Snapshot de nombres (para mostrar en UI incluso si producto cambia)
  product_name       VARCHAR(191) NOT NULL,
  variant_name       VARCHAR(191) NOT NULL,

  -- Cantidad
  quantity           INT NOT NULL,

  -- Modifiers como JSON (snapshot del momento de agregar al carrito)
  -- Estructura: [{"modifierOptionId": 101, "quantity": 1}, ...]
  modifiers_json     TEXT,

  -- Hash de modifiers para unicidad (SHA-256 del JSON ordenado)
  modifiers_hash     VARCHAR(64),

  -- Timestamps
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at         TIMESTAMP,

  -- Constraints
  CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id)
    REFERENCES cart(id) ON UPDATE RESTRICT ON DELETE CASCADE,
  CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id)
    REFERENCES product(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_cart_item_variant FOREIGN KEY (product_variant_id)
    REFERENCES product_variant(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_cart_item_quantity_positive CHECK (quantity >= 1 AND quantity <= 99),

  -- Unicidad: no duplicar items con misma variante y modifiers
  CONSTRAINT uk_cart_item_unique UNIQUE (cart_id, product_variant_id, modifiers_hash)
);

-- Índices para cart_item
CREATE INDEX IF NOT EXISTS idx_cart_item_cart ON cart_item (cart_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_variant ON cart_item (product_variant_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_active ON cart_item (cart_id, deleted_at);

-- ===============================
-- COMENTARIOS ADICIONALES
-- ===============================

COMMENT ON TABLE cart IS 'Carrito de compras persistente por usuario autenticado (S07-US01)';
COMMENT ON TABLE cart_item IS 'Items individuales del carrito con snapshot de producto/variante/modifiers';
COMMENT ON COLUMN cart_item.modifiers_json IS 'JSON array con modifiers: [{"modifierOptionId": 101, "quantity": 1}]';
COMMENT ON COLUMN cart_item.modifiers_hash IS 'Hash SHA-256 del JSON de modifiers para unicidad';
